Running Move unit tests
[ PASS    ] 0x42::m::t0
[ PASS    ] 0x42::m::t1
[ PASS    ] 0x42::m::t2
[ PASS    ] 0x42::m::t3
[ PASS    ] 0x42::m::t4
[ PASS    ] 0x42::m::t5
0x42::m::t0
Output: Ok("")
0x42::m::t1
Output: Ok("")
0x42::m::t2
Output: Ok("")
0x42::m::t3
Output: Ok("")
0x42::m::t4
Output: Ok("")
0x42::m::t5
Output: Ok("0x1:\n\t=> key 0x42::m::R {\n\t    dummy_field: false\n\t}\n")
Test result: OK. Total tests: 6; passed: 6; failed: 0
