Running Move unit tests
[ PASS    ] 0x1::B::tests_a
[ PASS    ] 0x1::B::tests_b
0x1::B::tests_a
Output: Ok("0x1:\n\t=> key 0x1::B::A<u64> {\n\t    t: 5\n\t}\n0x2:\n\t=> key 0x1::B::A<bool> {\n\t    t: false\n\t}\n")
0x1::B::tests_b
Output: Ok("0x1:\n\t=> key 0x1::B::A<u64> {\n\t    t: 5\n\t}\n0x2:\n\t=> key 0x1::B::A<u64> {\n\t    t: 6\n\t}\n")
Test result: OK. Total tests: 2; passed: 2; failed: 0
